services:
  - type: web
    name: journal-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: journal-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: UPLOAD_PATH
        value: uploads

databases:
  - name: journal-db
    databaseName: journal_app
    user: journal_user